# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region  = "eu-west-1"
  # Only these Account IDs may be operated on by this configuration
  allowed_account_ids = ["416912185826"]
  dynamic default_tags {
    for_each = toset(contains(["aws"], "aws") ? ["a"] : [])
    content {
      tags = {
        ENV = local.tg_environment
        TEAM = local.tg_team_name
        LEAF = "envs/dev/global/s3/default_bucket"
      }
    }
  }
}
