# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "atlantis-testing-repo-bucket-xyz"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "envs/dev/global/s3/default_bucket/terraform.tfstate"
    region         = "eu-west-1"
  }
}
